export interface RegistryItem {
  slug: string
  name: string
  type: 'ui' | 'block'
  githubUrl: string
  requires: string[]
}

const GITHUB_BASE = 'https://raw.githubusercontent.com/lithosui/Lithos_UI/main/src'

export const registry: Record<string, RegistryItem> = {
  accordion: {
    slug: 'accordion',
    name: 'Accordion',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Accordion.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx', 'components/ui/icons/IconChevronUp.tsx'],
  },
  alert: {
    slug: 'alert',
    name: 'Alert',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Alert.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'utils/colors.ts',
      'core/types.ts',
      'components/ui/Button.tsx',
      'components/ui/icons/IconUndo.tsx',
      'components/ui/icons/IconClose.tsx',
    ],
  },
  avatar: {
    slug: 'avatar',
    name: 'Avatar',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Avatar.tsx`,
    requires: ['utils/cn.ts', 'utils/yiq.ts', 'core/useAccentColor.ts'],
  },
  badge: {
    slug: 'badge',
    name: 'Badge',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Badge.tsx`,
    requires: ['utils/cn.ts', 'core/useAccentColor.ts', 'utils/yiq.ts', 'utils/colors.ts', 'core/types.ts'],
  },
  breadcrumb: {
    slug: 'breadcrumb',
    name: 'Breadcrumb',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Breadcrumb.tsx`,
    requires: [
      'utils/cn.ts',
      'components/ui/icons/IconHome.tsx',
      'components/ui/icons/IconBreadcrumbSeparator.tsx',
      'components/ui/icons/IconFolder.tsx',
      'components/ui/icons/IconSettings.tsx',
      'components/ui/icons/IconFileText.tsx',
    ],
  },
  button: {
    slug: 'button',
    name: 'Button',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Button.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'core/types.ts',
      'components/ui/icons/IconHome.tsx',
      'components/ui/icons/IconSettings.tsx',
      'components/ui/icons/IconDownload.tsx',
      'clsx',
      'tailwind-merge',
    ],
  },
  calendar: {
    slug: 'calendar',
    name: 'Calendar',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Calendar.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'core/types.ts',
      'utils/date.ts',
      'components/ui/Button.tsx',
      'components/ui/icons/IconChevronDown.tsx',
      'components/ui/icons/IconChevronLeft.tsx',
    ],
  },
  card: {
    slug: 'card',
    name: 'Card',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Card.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx'],
  },
  carousel: {
    slug: 'carousel',
    name: 'Carousel',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/carousel/Carousel.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/scrollTo.ts',
      'components/ui/Button.tsx',
      'components/ui/carousel/CarouselButton.tsx',
      'components/ui/carousel/CarouselControls.tsx',
      'components/ui/carousel/CarouselSlide.tsx',
      'components/ui/carousel/CarouselPagination.tsx',
      'components/ui/carousel/CarouselTrack.tsx',
      'components/ui/carousel/useCarousel.ts',
      'components/ui/carousel/useCarouselDrag.ts',
      'components/ui/carousel/carousel.types.ts',
      'components/ui/icons/IconArrowLeft.tsx',
      'components/ui/icons/IconArrowRight.tsx',
      'components/ui/icons/IconArrowDown.tsx',
      'components/ui/icons/IconArrowUp.tsx',
      'components/ui/icons/IconCircle.tsx',
    ],
  },
  checkbox: {
    slug: 'checkbox',
    name: 'Checkbox',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Checkbox.tsx`,
    requires: ['utils/cn.ts', 'utils/yiq.ts', 'core/types.ts'],
  },
  dialog: {
    slug: 'dialog',
    name: 'Dialog',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Dialog.tsx`,
    requires: [
      'components/ui/icons/IconClose.tsx',
      'components/ui/icons/IconSettings.tsx',
      'components/ui/icons/IconAlertTriangle.tsx',
      'components/ui/Button.tsx',
      'core/hooks/useFocusTrap.ts',
      'core/types.ts',
      'utils/cn.ts',
    ],
  },
  'dropdown-menu': {
    slug: 'dropdown-menu',
    name: 'Dropdown Menu',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/dropdown/DropdownMenu.tsx`,
    requires: [
      'utils/cn.ts',
      'components/ui/Button.tsx',
      'components/ui/dropdown/DropdownMenuContent.tsx',
      'components/ui/dropdown/DropdownMenuItem.tsx',
      'components/ui/dropdown/DropdownMenuGroup.tsx',
      'components/ui/dropdown/DropdownMenuSeparator.tsx',
      'components/ui/dropdown/DropdownMenuTrigger.tsx',
      'components/ui/dropdown/DropdownMenuClose.tsx',
      'components/ui/dropdown/useDropdown.ts',
    ],
  },
  input: {
    slug: 'input',
    name: 'Input',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Input.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/colors.ts',
      'components/ui/icons/IconSearch.tsx',
      'components/ui/icons/IconSettings.tsx',
    ],
  },
  popover: {
    slug: 'popover',
    name: 'Popover',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Popover.tsx`,
    requires: ['@floating-ui/react', 'utils/cn.ts', 'components/ui/Button.tsx'],
  },
  select: {
    slug: 'select',
    name: 'Select',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/select/Select.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'core/useAccentColor.ts',
      'components/ui/Button.tsx',
      'components/ui/Popover.tsx',
      'components/ui/popover/PopoverContent.tsx',
      'components/ui/popover/PopoverTrigger.tsx',
      'components/ui/popover/usePopover.ts',
      'components/ui/icons/IconChevronDown.tsx',
      'components/ui/select/SelectTrigger.tsx',
      'components/ui/select/SelectContent.tsx',
      'components/ui/select/SelectItem.tsx',
      'components/ui/select/useSelect.ts',
      'components/ui/select/select.types.ts',
      '@floating-ui/react',
      'core/hooks/useVirtualizer.ts',
    ],
  },
  tabs: {
    slug: 'tabs',
    name: 'Tabs',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Tabs.tsx`,
    requires: ['utils/cn.ts'],
  },
  toast: {
    slug: 'toast',
    name: 'Toast',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Toast.tsx`,
    requires: [
      'components/ui/icons/IconClose.tsx',
      'components/ui/Button.tsx',
      'core/hooks/useToast.ts',
      'core/types.ts',
      'utils/colors.ts',
      'utils/yiq.ts',
      'utils/cn.ts',
    ],
  },
  toggle: {
    slug: 'toggle',
    name: 'Toggle',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Toggle.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx'],
  },
  tooltip: {
    slug: 'tooltip',
    name: 'Tooltip',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Tooltip.tsx`,
    requires: ['utils/cn.ts', '@floating-ui/react'],
  },

  // Blocks
  'faq-1': {
    slug: 'faq-1',
    name: 'Standard FAQ',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/FAQ/1.tsx`,
    requires: ['components/ui/Accordion.tsx'],
  },
  'feature-grids-1': {
    slug: 'feature-grids-1',
    name: 'Classic Grid',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/FeatureGrid/1.tsx`,
    requires: ['components/ui/Card.tsx'],
  },
  'footer-1': {
    slug: 'footer-1',
    name: 'Multi-column Footer',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Footer/1.tsx`,
    requires: [],
  },
  'footer-2': {
    slug: 'footer-2',
    name: 'Minimal Footer',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Footer/2.tsx`,
    requires: [],
  },
  'hero-1': {
    slug: 'hero-1',
    name: 'Standard Hero',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Hero/1.tsx`,
    requires: ['components/ui/Badge.tsx', 'components/ui/Button.tsx'],
  },
  'hero-2': {
    slug: 'hero-2',
    name: 'Split Layout Hero',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Hero/2.tsx`,
    requires: ['components/ui/Badge.tsx', 'components/ui/Button.tsx', 'components/ui/Card.tsx'],
  },
  'navbar-1': {
    slug: 'navbar-1',
    name: 'Standard Navbar',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Navbar/1.tsx`,
    requires: ['components/ui/Button.tsx', 'components/ui/icons/IconMenu.tsx', 'components/ui/icons/IconClose.tsx'],
  },
  'pricing-1': {
    slug: 'pricing-1',
    name: '3-Tier Grid',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Pricing/1.tsx`,
    requires: ['components/ui/Card.tsx', 'components/ui/Button.tsx', 'utils/cn.ts'],
  },
  'testimonials-1': {
    slug: 'testimonials-1',
    name: 'Standard Grid',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Testimonials/1.tsx`,
    requires: ['components/ui/Card.tsx', 'components/ui/Avatar.tsx'],
  },
}
